#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

search --set -f /.winboot
if [ -f /.winboot ]; then
	search --no-floppy --fs-uuid --set=root 6692-D14E
	chainloader /efi/Microsoft/Boot/bootmgfw-grub.efi
	boot
fi
